version: "3.8"

services:
  bitcoin-testnet:
    image: kylemanna/bitcoind:latest
    container_name: bitcoin-testnet-node
    ports:
      - "18332:18332" # RPC port
      - "18333:18333" # P2P port
    volumes:
      - bitcoin-testnet-data:/bitcoin/.bitcoin
      - ./docker/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    environment:
      - BITCOIN_DATA=/bitcoin/.bitcoin
    command: >
      bitcoind
      -conf=/bitcoin/.bitcoin/bitcoin.conf
      -printtoconsole
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0:18332
      -listen=1
      -server=1
      -txindex=1
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "bitcoin-cli",
          "-conf=/bitcoin/.bitcoin/bitcoin.conf",
          "getblockchaininfo",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  bitcoin-testnet-faucet:
    image: node:18-alpine
    container_name: bitcoin-testnet-faucet
    ports:
      - "3001:3001"
    volumes:
      - ./docker/faucet:/app
    working_dir: /app
    environment:
      - BITCOIN_RPC_URL=http://bitcoin-testnet:18332
      - BITCOIN_RPC_USER=test
      - BITCOIN_RPC_PASS=test
      - FAUCET_PORT=3001
    depends_on:
      bitcoin-testnet:
        condition: service_healthy
    command: >
      sh -c "
        npm install &&
        npm start
      "
    restart: unless-stopped

  # Tron local testnet (like Anvil for Tron)
  tron-local:
    image: trontools/quickstart
    container_name: tron-local
    ports:
      - "9090:9090" # HTTP API
      - "8090:8090" # FullNode
      - "6060:6060" # SolidityNode
    restart: unless-stopped

volumes:
  bitcoin-testnet-data:
    driver: local
