[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Compiler settings
solc_version = "0.8.7"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = false
bytecode_hash = "none"

# Testing settings
verbosity = 2
gas_reports = ["*"]

# Tron network settings
[rpc_endpoints]
tron_nile = "https://nile.trongrid.io"
tron_mainnet = "https://api.trongrid.io"
